package krug.daan.easynosql.dynamodb.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * @author Daniel Augusto Krug
 * 
 * Class to handling of relations between stored objects.
 */
@DynamoDBTable(tableName="RelationalIntegrityDTO")
public class RelationalIntegrityDTO extends BaseDTO {
	
	/**
	 * OWNER_TABLE_NAME
	 */
	public static final String OWNER_TABLE_NAME = "ownerTableName";
	
	/**
	 * OWNER_ID
	 */
	public static final String OWNER_ID = "ownerId";
	
	/**
	 * RELATED_TABLE_NAME
	 */
	public static final String RELATED_TABLE_NAME = "relatedTableName";
	
	/**
	 * RELATED_ID
	 */
	public static final String RELATED_ID = "relatedId";
	
	/**
	 * Constructor
	 */
	public RelationalIntegrityDTO(){
		super(RelationalIntegrityDTO.class);
	}
	
	/**
	 * Table name of object owner. 
	 * Owner contains the relational reference to related object
	 * in the [relatedObjectsIds] attribute.
	 */
	private String ownerTableName;
	
	/**
	 * "id" value of object owner. 
	 * Owner contains the relational reference to related object
	 * in the [relatedObjectsIds] attribute.
	 */
	private String ownerId;
	
	/**
	 * Table name of related object on owner object
	 */
	private String relatedTableName;
	
	/**
	 * "id" value of related object on owner object
	 */
	private String relatedId;
	
	/**
	 * @return ownerTableName
	 */
	@DynamoDBAttribute(attributeName = "ownerTableName")
	public String getOwnerTableName() {
		return ownerTableName;
	}
	
	/**
	 * Set the ownerTableName
	 * @param ownerTableName
	 */
	public void setOwnerTableName(String ownerTableName) {
		this.ownerTableName = ownerTableName;
	}
	
	/**
	 * @return ownerId
	 */
	@DynamoDBAttribute(attributeName = "ownerId")
	public String getOwnerId() {
		return ownerId;
	}
	
	/**
	 * Set the ownerId
	 * @param ownerId
	 */
	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}
	
	/**
	 * @return relatedTableName
	 */
	@DynamoDBAttribute(attributeName = "relatedTableName")
	public String getRelatedTableName() {
		return relatedTableName;
	}
	
	/**
	 * Set the relatedTableName
	 * @param relatedTableName
	 */
	public void setRelatedTableName(String relatedTableName) {
		this.relatedTableName = relatedTableName;
	}
	
	/**
	 * @return relatedId
	 */
	@DynamoDBAttribute(attributeName = "relatedId")
	public String getRelatedId() {
		return relatedId;
	}
	
	/**
	 * Set the relatedId
	 * @param relatedId
	 */
	public void setRelatedId(String relatedId) {
		this.relatedId = relatedId;
	}
	
	/**
	 * @return id
	 */
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAttribute(attributeName = "id")
	@Override
	public String getId() {
		return id;
	}
	
	/**
	 * Set the id
	 * @param id
	 */
	@Override
	public void setId(String id) {
		this.id = id;
	}
	
	/**
	 * @return tableName
	 */
	@DynamoDBAttribute(attributeName = "tableName")
	@Override
	public String getTableName() {
		return tableName;
	}
	
	/**
	 * Set the tableName
	 * @param tableName
	 */
	@Override
	public void setTableName(String tableName){
		this.tableName = tableName;
	}
	
	/**
	 * @return relatedObjectsIdsJson
	 */
	@DynamoDBAttribute(attributeName = "relatedObjectsIdsJson")
	@Override
	public String getRelatedObjectsIdsJson() {
		return relatedObjectsIdsJson;
	}
	
	/**
	 * Set the relatedObjectsIdsJson
	 * @param relatedObjectsIdsJson
	 */
	@Override
	public void setRelatedObjectsIdsJson(String relatedObjectsIdsJson) {
		this.relatedObjectsIdsJson = relatedObjectsIdsJson;
	}
}
