package app.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import krug.daan.easynosql.dynamodb.dto.BaseDTO;


@DynamoDBTable(tableName="DynamoUser")
public class DynamoUser  extends BaseDTO{
	
	public DynamoUser(){
		super(DynamoUser.class);
	}
	
	
	private String name;
	
	private String email;
	
	private Integer yearsOld;
	
	private java.util.Date created;
	
	private Long points;
	
	private Double rating;
	
	@DynamoDBAttribute(attributeName = "name")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute(attributeName = "email")
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@DynamoDBAttribute(attributeName = "yearsOld")
	public Integer getYearsOld() {
		return yearsOld;
	}
	public void setYearsOld(Integer old) {
		this.yearsOld = old;
	}
	@DynamoDBAttribute(attributeName = "created")
	public java.util.Date getCreated() {
		return created;
	}
	public void setCreated(java.util.Date created) {
		this.created = created;
	}
	@DynamoDBAttribute(attributeName = "points")
	public Long getPoints() {
		return points;
	}
	public void setPoints(Long points) {
		this.points = points;
	}
	@DynamoDBAttribute(attributeName = "rating")
	public Double getRating() {
		return rating;
	}
	public void setRating(Double rating) {
		this.rating = rating;
	}
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAttribute(attributeName = "id")
	@Override
	public String getId() {
		return id;
	}
	@Override
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName = "tableName")
	@Override
	public String getTableName() {
		return tableName;
	}
	@Override
	public void setTableName(String tableName){
		this.tableName = tableName;
	}
	
	@DynamoDBAttribute(attributeName = "relatedObjectsIdsJson")
	@Override
	public String getRelatedObjectsIdsJson() {
		return relatedObjectsIdsJson;
	}
	@Override
	public void setRelatedObjectsIdsJson(String relatedObjectsIdsJson) {
		this.relatedObjectsIdsJson = relatedObjectsIdsJson;
	}

}
